---
abstract: 'Toolkit for correct daemonization'
author:
  - 'Shamatrin Dmitriy'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: System-Daemon
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
resources:
  repository: https://github.com/justnoxx/system-daemon
version: 0.11
